### GET request to example server
GET http://localhost:8080/api/runs

###
GET http://localhost:8080/api/runs/4

###
POST http://localhost:8080/api/runs
Content-Type: application/json

{
  "id": 3,
  "title": "Third",
  "started": "2025-09-19T23:36:10.9562289",
  "completed": "2025-09-20T00:36:10.9562289",
  "miles": 12,
  "location": "OUTDOORS"
}


###
PUT http://localhost:8080/api/runs/1
Content-Type: application/json

{
  "id": 2,
  "title": "Third",
  "started": "2025-09-19T23:36:10.9562289",
  "completed": "2025-10-19T00:36:10.9562289",
  "miles": 4,
  "location": "OUTDOORS"
}

###
DELETE http://localhost:8080/api/runs/1

###
GET http://localhost:8080/api/runs/location/OUTDOORS